"""add card costs

Revision ID: 1f974818720f
Revises: 3730c2fb7e84
Create Date: 2016-10-04 13:05:51.783832

"""

# revision identifiers, used by Alembic.
revision = '1f974818720f'
down_revision = '3730c2fb7e84'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('cost_in_debt', sa.Integer(), nullable=False))
    op.add_column('card', sa.Column('cost_in_treasure', sa.Integer(), nullable=False))
    op.add_column('card', sa.Column('is_in_supply', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'is_in_supply')
    op.drop_column('card', 'cost_in_treasure')
    op.drop_column('card', 'cost_in_debt')
    ### end Alembic commands ###
