"""remove card type text

Revision ID: 39a72c144eaa
Revises: 1f974818720f
Create Date: 2016-10-04 13:08:57.416038

"""

# revision identifiers, used by Alembic.
revision = '39a72c144eaa'
down_revision = '1f974818720f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('type', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    ### end Alembic commands ###
