"""add card.type

Revision ID: e7a0ff5cc43c
Revises: cea0f95640fb
Create Date: 2016-09-27 14:33:16.971186

"""

# revision identifiers, used by Alembic.
revision = 'e7a0ff5cc43c'
down_revision = 'cea0f95640fb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('type', sa.String(length=1024), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'type')
    ### end Alembic commands ###
